import Nav from '@/components/Nav'
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Posting',
  description: 'Generated by create Posting app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#242424]`}>
        <div className='mx-auto w-full md:w-[650px]'>

          <Nav />
          {children}
        </div>
      </body>
    </html>
  )
}
